project_id = "kfanwlpemesqvquypqvh"

[functions.review-report-attachment]
verify_jwt = false

[functions.email-verification-otp]
verify_jwt = false

[functions.direct-password-reset]
verify_jwt = false

[functions.send-report-push]
verify_jwt = false

[functions.send-report-status-email]
verify_jwt = false

[functions.send-account-update-email]
verify_jwt = false
