import { StyleSheet } from "react-native";

// Styles for the face selfie capture screen
// (app/verification/face_selfie/cameraface_selfie/selfiecapture.tsx).
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0F172A",
  },
  containerIdle: {
    alignItems: "center",
    justifyContent: "center",
  },
  backButton: {
    position: "absolute",
    top: 48,
    left: 24,
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "#0EA5E9",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
    shadowColor: "#0EA5E9",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  faceGuide: {
    position: "absolute",
    top: "18%",
    alignSelf: "center",
    width: 280,
    height: 340,
  },
  faceGuideCornerTL: {
    position: "absolute",
    top: 0,
    left: 0,
    width: 48,
    height: 48,
    borderTopWidth: 4,
    borderLeftWidth: 4,
    borderTopColor: "#0EA5E9",
    borderLeftColor: "#0EA5E9",
    borderTopLeftRadius: 24,
  },
  faceGuideCornerTR: {
    position: "absolute",
    top: 0,
    right: 0,
    width: 48,
    height: 48,
    borderTopWidth: 4,
    borderRightWidth: 4,
    borderTopColor: "#0EA5E9",
    borderRightColor: "#0EA5E9",
    borderTopRightRadius: 24,
  },
  faceGuideCornerBL: {
    position: "absolute",
    bottom: 0,
    left: 0,
    width: 48,
    height: 48,
    borderBottomWidth: 4,
    borderLeftWidth: 4,
    borderBottomColor: "#0EA5E9",
    borderLeftColor: "#0EA5E9",
    borderBottomLeftRadius: 24,
  },
  faceGuideCornerBR: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 48,
    height: 48,
    borderBottomWidth: 4,
    borderRightWidth: 4,
    borderBottomColor: "#0EA5E9",
    borderRightColor: "#0EA5E9",
    borderBottomRightRadius: 24,
  },
  faceGuideCornerActive: {
    borderTopColor: "#22C55E",
    borderLeftColor: "#22C55E",
    borderRightColor: "#22C55E",
    borderBottomColor: "#22C55E",
  },
  hintText: {
    position: "absolute",
    bottom: 130,
    alignSelf: "center",
    fontSize: 15,
    color: "#FFFFFF",
    backgroundColor: "rgba(15, 23, 42, 0.55)",
    overflow: "hidden",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
  },
  hintTextWarn: {
    backgroundColor: "rgba(190, 18, 60, 0.75)",
  },
  captureButton: {
    position: "absolute",
    bottom: 40,
    alignSelf: "center",
    width: 76,
    height: 76,
    borderRadius: 38,
    borderWidth: 4,
    borderColor: "#FFFFFF",
    backgroundColor: "rgba(255, 255, 255, 0.35)",
    alignItems: "center",
    justifyContent: "center",
  },
  captureButtonInner: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: "#FFFFFF",
  },
  captureButtonDisabled: {
    borderColor: "#94A3B8",
    backgroundColor: "rgba(148, 163, 184, 0.35)",
  },
  captureButtonInnerDisabled: {
    backgroundColor: "#94A3B8",
  },
  idleContent: {
    alignItems: "center",
    paddingHorizontal: 32,
  },
  idleText: {
    fontSize: 15,
    color: "#94A3B8",
    marginTop: 16,
    textAlign: "center",
  },
  allowButton: {
    marginTop: 24,
    backgroundColor: "#0EA5E9",
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 32,
  },
  allowButtonText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#FFFFFF",
  },
});
