import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },
  headerBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    paddingVertical: 14,
    backgroundColor: "#F8FAFC",
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  headerLogo: {
    width: 32,
    height: 32,
    resizeMode: "contain",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    transform: [{ scale: 2 }],
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: "#0F172A",
    letterSpacing: -0.5,
  },
  scrollContent: {
    paddingBottom: 160,
    paddingHorizontal: 20,
    paddingTop: 8,
  },
  heroCard: {
    backgroundColor: "#0284C7",
    borderRadius: 24,
    marginBottom: 24,
    overflow: "hidden",
    shadowColor: "#0284C7",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  heroOverlay: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 28,
    backgroundColor: "rgba(255,255,255,0.05)",
  },
  heroTextContainer: {
    flex: 1,
    zIndex: 2,
  },
  heroWelcome: {
    color: "#BAE6FD",
    fontSize: 15,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  heroName: {
    color: "#FFFFFF",
    fontSize: 28,
    fontWeight: "900",
    marginTop: 6,
    letterSpacing: -0.5,
  },
  heroSubtitle: {
    color: "#E0F2FE",
    fontSize: 14,
    marginTop: 8,
    fontWeight: "400",
    opacity: 0.9,
  },
  heroIconContainer: {
    position: "absolute",
    right: -20,
    bottom: -20,
    zIndex: 1,
  },
  primaryActionCard: {
    flexDirection: "row",
    backgroundColor: "#509AEE",
    borderRadius: 20,
    padding: 20,
    marginBottom: 32,
    alignItems: "center",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 3,
    borderWidth: 1,
    borderColor: "#3a7ac4",
  },
  primaryActionIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#a0eeba9d",
    shadowColor: "#0EA5E9",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  primaryActionTextWrap: {
    flex: 1,
    marginLeft: 16,
    marginRight: 12,
  },
  primaryActionTitle: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 4,
    letterSpacing: -0.3,
  },
  primaryActionDesc: {
    color: "#ffffff",
    fontSize: 13,
    lineHeight: 18,
  },
  sectionLabel: {
    fontSize: 14,
    fontWeight: "800",
    color: "#334155",
    marginBottom: 16,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  utilitiesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 16,
  },
  gridCard: {
    width: "47%",
    backgroundColor: "#509AEE",
    borderRadius: 20,
    padding: 20,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 1,
    borderColor: "#3a7ac4",
    alignItems: "flex-start",
  },
  gridCardFull: {
    width: "100%",
  },
  fullCardContent: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
  },
  fullCardText: {
    flex: 1,
    marginLeft: 16,
  },
  gridIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
  },
  gridTitle: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "800",
    marginBottom: 6,
    letterSpacing: -0.3,
  },
  gridDesc: {
    color: "#ffffff",
    fontSize: 13,
    lineHeight: 18,
  },
  aiFab: {
    position: "absolute",
    right: 24,
    bottom: 100,
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#0284C7",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#0284C7",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 8,
  },
});
