import { StyleSheet } from "react-native";

// Styles for the Valid ID capture screen
// (app/verification/valid_id/validid_cam/valididcapture.tsx).
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0F172A",
  },
  containerIdle: {
    alignItems: "center",
    justifyContent: "center",
  },
  sideTitle: {
    position: "absolute",
    top: 104,
    alignSelf: "center",
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
    textAlign: "center",
  },
  // ID cards are 85.6mm × 54mm ≈ 1.586:1, so the guide is a landscape
  // rectangle (unlike the portrait face frame) to match the document shape.
  idGuide: {
    position: "absolute",
    top: "30%",
    alignSelf: "center",
    width: "88%",
    aspectRatio: 1.586,
  },
  guideCornerTL: {
    position: "absolute",
    top: 0,
    left: 0,
    width: 44,
    height: 44,
    borderTopWidth: 4,
    borderLeftWidth: 4,
    borderTopColor: "#0EA5E9",
    borderLeftColor: "#0EA5E9",
    borderTopLeftRadius: 12,
  },
  guideCornerTR: {
    position: "absolute",
    top: 0,
    right: 0,
    width: 44,
    height: 44,
    borderTopWidth: 4,
    borderRightWidth: 4,
    borderTopColor: "#0EA5E9",
    borderRightColor: "#0EA5E9",
    borderTopRightRadius: 12,
  },
  guideCornerBL: {
    position: "absolute",
    bottom: 0,
    left: 0,
    width: 44,
    height: 44,
    borderBottomWidth: 4,
    borderLeftWidth: 4,
    borderBottomColor: "#0EA5E9",
    borderLeftColor: "#0EA5E9",
    borderBottomLeftRadius: 12,
  },
  guideCornerBR: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 44,
    height: 44,
    borderBottomWidth: 4,
    borderRightWidth: 4,
    borderBottomColor: "#0EA5E9",
    borderRightColor: "#0EA5E9",
    borderBottomRightRadius: 12,
  },
  hintText: {
    position: "absolute",
    bottom: 130,
    alignSelf: "center",
    fontSize: 14,
    color: "#FFFFFF",
    backgroundColor: "rgba(15, 23, 42, 0.55)",
    overflow: "hidden",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    textAlign: "center",
  },
  hintTextWarn: {
    backgroundColor: "rgba(190, 18, 60, 0.75)",
  },
  captureButton: {
    position: "absolute",
    bottom: 40,
    alignSelf: "center",
    width: 76,
    height: 76,
    borderRadius: 38,
    borderWidth: 4,
    borderColor: "#FFFFFF",
    backgroundColor: "rgba(255, 255, 255, 0.35)",
    alignItems: "center",
    justifyContent: "center",
  },
  captureButtonInner: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: "#FFFFFF",
  },
  captureButtonDisabled: {
    borderColor: "#94A3B8",
    backgroundColor: "rgba(148, 163, 184, 0.35)",
  },
  idleText: {
    fontSize: 15,
    color: "#94A3B8",
    marginTop: 16,
    textAlign: "center",
  },
  allowButton: {
    marginTop: 24,
    backgroundColor: "#0EA5E9",
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 32,
  },
  allowButtonText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#FFFFFF",
  },
});
